export const FETCHING_CURRENT_LEASES = 'FETCHING_CURRENT_LEASES'; 
export const FETCH_CURRENT_LEASES_SUCCESS = 'FETCH_CURRENT_LEASES_SUCCESS';
export const FETCH_CURRENT_LEASES_ERROR = 'FETCH_CURRENT_LEASES_ERROR';
export const FETCHING_SELECTED_LEASE = 'FETCHING_SELECTED_LEASE';
export const FETCH_SELECTED_LEASE_SUCCESS = 'FETCH_SELECTED_LEASE_SUCCESS';
export const FETCH_SELECTED_LEASE_ERROR = 'FETCH_SELECTED_LEASE_ERROR';