export const FETCHING_CURRENT_LEASES = 'FETCHING_CURRENT_LEASES'; 
export const FETCH_CURRENT_LEASES_SUCCESS = 'FETCH_CURRENT_LEASES_SUCCESS';
export const FETCH_CURRENT_LEASES_ERROR = 'FETCH_CURRENT_LEASES_ERROR';